Repository Navideck/universal_ble, pull requests merged in 2024-09, with the labels that each got.

#78 Improve scan filter api
  .vscode/settings.json
  CHANGELOG.md
  README.md
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBle.g.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBleFilterUtil.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt
  darwin/Classes/UniversalBle.g.swift
  darwin/Classes/UniversalBleFilterUtil.swift
  darwin/Classes/UniversalBleHelper.swift
  darwin/Classes/UniversalBlePlugin.swift
  example/lib/data/mock_universal_ble.dart
  example/lib/home/home.dart
  example/lib/home/widgets/scanned_item_widget.dart
  example/lib/peripheral_details/peripheral_detail_page.dart
  example/pubspec.lock
  lib/src/models/ble_device.dart
  lib/src/models/manufacturer_data.dart
  lib/src/models/model_exports.dart
  lib/src/models/platform_config.dart
  lib/src/models/scan_filter.dart
  lib/src/universal_ble_filter_util.dart
  lib/src/universal_ble_linux/universal_ble_linux.dart
  lib/src/universal_ble_pigeon/universal_ble.g.dart
  lib/src/universal_ble_pigeon/universal_ble_pigeon_channel.dart
  lib/src/universal_ble_platform_interface.dart
  lib/src/universal_ble_web/universal_ble_web.dart
  pigeon/universal_ble.dart
  pubspec.yaml
  test/scan_filter_test.dart
  windows/CMakeLists.txt
  windows/src/generated/universal_ble.g.cpp
  windows/src/generated/universal_ble.g.h
  windows/src/helper/utils.cpp
  windows/src/universal_ble_filter_util.cpp
  windows/src/universal_ble_filter_util.h
  windows/src/universal_ble_plugin.cpp
  windows/src/universal_ble_plugin.h
Labels: documentation, enhancement, Review effort [1-5]: 4, Tests

#85 Make supportsInAppPairing more accurate
  lib/src/models/ble_capabilities.dart
  lib/src/universal_ble.dart
Labels: enhancement, Review effort [1-5]: 2

#88 Rename in-app pairing capabilities
  CHANGELOG.md
  example/lib/peripheral_details/peripheral_detail_page.dart
  lib/src/models/ble_capabilities.dart
  lib/src/universal_ble_pigeon/universal_ble.g.dart
Labels: documentation, enhancement, Review effort [1-5]: 3

#89 Add error in connection updates
  CHANGELOG.md
  README.md
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBle.g.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt
  darwin/Classes/UniversalBle.g.swift
  darwin/Classes/UniversalBleHelper.swift
  darwin/Classes/UniversalBlePlugin.swift
  example/lib/peripheral_details/peripheral_detail_page.dart
  lib/src/models/ble_connection_update.dart
  lib/src/models/ble_service.dart
  lib/src/models/model_exports.dart
  lib/src/universal_ble.dart
  lib/src/universal_ble_exceptions.dart
  lib/src/universal_ble_linux/universal_ble_linux.dart
  lib/src/universal_ble_pigeon/universal_ble.g.dart
  lib/src/universal_ble_pigeon/universal_ble_pigeon_channel.dart
  lib/src/universal_ble_platform_interface.dart
  lib/src/universal_ble_web/universal_ble_web.dart
  lib/src/universal_logger.dart
  lib/universal_ble.dart
  pigeon/universal_ble.dart
  pubspec.yaml
  windows/src/generated/universal_ble.g.cpp
  windows/src/generated/universal_ble.g.h
  windows/src/universal_ble_plugin.cpp
Labels: enhancement, Bug fix, Review effort [1-5]: 3
