Repository Navideck/universal_ble, pull requests merged in 2024-06, with the labels that each got.

#48 Add queue per device
  CHANGELOG.md
  README.md
  example/lib/home/home.dart
  lib/src/ble_command_queue.dart
  lib/src/models/model_exports.dart
  lib/src/models/queue_type.dart
  lib/src/queue.dart
  lib/src/universal_ble.dart
  lib/src/universal_ble_platform_interface.dart
  lib/universal_ble.dart
  pubspec.yaml
Labels: documentation, enhancement, Review effort [1-5]: 3

#46 Implement pairing with dialog on windows
  .vscode/settings.json
  CHANGELOG.md
  example/lib/peripheral_details/peripheral_detail_page.dart
  example/pubspec.lock
  lib/src/universal_ble.dart
  lib/src/universal_ble_pigeon/universal_ble.g.dart
  lib/src/universal_ble_pigeon/universal_ble_pigeon_channel.dart
  windows/CMakeLists.txt
  windows/src/helper/utils.cpp
  windows/src/helper/utils.h
  windows/src/pin_entry.h
  windows/src/universal_ble_plugin.cpp
  windows/src/universal_ble_plugin.h
Labels: Review effort [1-5]: 4

#51 Set CBCentralManagerScanOptionAllowDuplicatesKey to true
  CHANGELOG.md
  darwin/Classes/UniversalBlePlugin.swift
Labels: enhancement, Review effort [1-5]: 2

#53 Do not initialize global queue if not needed
  lib/src/ble_command_queue.dart
  lib/src/universal_ble.dart
Labels: Review effort [1-5]: 3
