Repository Navideck/universal_ble, pull requests merged in 2024-07, with the labels that each got.

#60 Improve error handling and disconnection events
  CHANGELOG.md
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt
  darwin/Classes/UniversalBlePlugin.swift
  pubspec.yaml
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#61 Implement scan filter in example app
  .github/workflows/build_web_app.yml
  example/.gitignore
  example/.metadata
  example/lib/home/home.dart
  example/lib/home/widgets/scan_filter_widget.dart
  example/lib/peripheral_details/peripheral_detail_page.dart
  example/pubspec.lock
  example/pubspec.yaml
  example/web/index.html
Labels: enhancement, Review effort [1-5]: 3, Other

#62 Improve BleUuid API and tests
  .github/workflows/test_ble_uuid_parser.yml
  CHANGELOG.md
  README.md
  example/lib/home/home.dart
  example/lib/home/widgets/scan_filter_widget.dart
  lib/src/models/ble_service.dart
  lib/src/models/ble_uuid_parser.dart
  lib/src/models/model_exports.dart
  lib/src/universal_ble.dart
  lib/src/universal_ble_pigeon/universal_ble_pigeon_channel.dart
  lib/src/universal_ble_platform_interface.dart
  test/ble_uuid_parser_test.dart
  test/universal_ble_test.dart
Labels: enhancement, Review effort [1-5]: 3, Tests

#63 Receive advertisement events on web
  .vscode/launch.json
  CHANGELOG.md
  README.md
  example/lib/home/home.dart
  example/lib/home/widgets/scan_filter_widget.dart
  example/lib/peripheral_details/peripheral_detail_page.dart
  example/pubspec.lock
  lib/src/models/ble_device.dart
  lib/src/universal_ble.dart
  lib/src/universal_ble_platform_interface.dart
  lib/src/universal_ble_web/universal_ble_web.dart
Labels: documentation, enhancement, Bug fix, Review effort [1-5]: 3

#66 Improve web support
  example/lib/peripheral_details/peripheral_detail_page.dart
  lib/src/universal_ble_web/universal_ble_web.dart
Labels: enhancement, Bug fix, Review effort [1-5]: 3
