Repository Navideck/universal_ble, pull requests merged in 2024-05, with the labels that each got.

#38 Improve manufacturer data discovery on Windows
  CHANGELOG.md
  example/lib/home/widgets/scanned_item_widget.dart
  example/lib/peripheral_details/peripheral_detail_page.dart
  pubspec.yaml
  windows/src/universal_ble_plugin.cpp
  windows/src/universal_ble_plugin.h
Labels: enhancement, Review effort [1-5]: 3

#40 Improve Apple, Android and Windows
  CHANGELOG.md
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt
  darwin/Classes/UniversalBlePlugin.swift
  example/lib/home/home.dart
  example/macos/Podfile.lock
  example/macos/Runner.xcodeproj/project.pbxproj
  example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  pubspec.yaml
  windows/src/universal_ble_plugin.cpp
Labels: enhancement, Review effort [1-5]: 2

#42 Improve setNotifiation completion
  CHANGELOG.md
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBle.g.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt
  darwin/Classes/UniversalBle.g.swift
  darwin/Classes/UniversalBleHelper.swift
  darwin/Classes/UniversalBlePlugin.swift
  example/ios/Podfile.lock
  example/ios/Runner.xcodeproj/project.pbxproj
  example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  example/pubspec.lock
  lib/src/universal_ble_pigeon/universal_ble.g.dart
  lib/src/universal_ble_pigeon/universal_ble_pigeon_channel.dart
  pigeon/universal_ble.dart
  pubspec.yaml
  windows/src/generated/universal_ble.g.cpp
  windows/src/generated/universal_ble.g.h
  windows/src/universal_ble_plugin.cpp
  windows/src/universal_ble_plugin.h
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#43 Remove dependency on collection
  CHANGELOG.md
  lib/src/universal_ble_linux/universal_ble_linux.dart
  pubspec.yaml
Labels: enhancement, Review effort [1-5]: 2

#45 Add name filter
  CHANGELOG.md
  README.md
  example/lib/home/widgets/scanned_item_widget.dart
  lib/src/models/scan_filter.dart
  lib/src/universal_ble_linux/universal_ble_linux.dart
  lib/src/universal_ble_pigeon/universal_ble_pigeon_channel.dart
  lib/src/universal_ble_platform_interface.dart
  lib/src/universal_ble_web/universal_ble_web.dart
  pubspec.yaml
Labels: enhancement
