Repository Navideck/universal_ble, pull requests merged in 2024-12, with the labels that each got.

#102 Bump flutter_web_bluetooth to 1.0.0
  CHANGELOG.md
  example/pubspec.lock
  pubspec.yaml
Labels: Review effort [1-5]: 1

#106 Fix android cleanup after disconnection
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt
Labels: Review effort [1-5]: 1

#103 Improve Darwin Manager Initialization
  CHANGELOG.md
  darwin/Classes/UniversalBlePlugin.swift
  example/macos/Podfile.lock
  lib/src/universal_ble_pigeon/universal_ble_pigeon_channel.dart
Labels: Review effort [1-5]: 2

#104 Handle Android scan abuse
  android/src/main/kotlin/com/navideck/universal_ble/SafeScanner.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt
Labels: Review effort [1-5]: 2

#109 Fix Android cleanup on gatt disconnect
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt
Labels: Review effort [1-5]: 2

#110 Remove "Characteristic already notifying" error
  lib/src/universal_ble_linux/universal_ble_linux.dart
  lib/src/universal_ble_web/universal_ble_web.dart
Labels: Review effort [1-5]: 2

#112 Fix Windows Bluetooth availability state in Release build
  .vscode/launch.json
  windows/src/universal_ble_plugin.cpp
Labels: Review effort [1-5]: 3

#111 Fix Windows filter with services
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBleFilterUtil.kt
  darwin/Classes/UniversalBlePlugin.swift
  windows/src/universal_ble_plugin.cpp
Labels: Review effort [1-5]: 2

#113 Add API to disable Bluetooth
  README.md
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBle.g.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt
  darwin/Classes/UniversalBle.g.swift
  darwin/Classes/UniversalBlePlugin.swift
  example/lib/data/mock_universal_ble.dart
  example/lib/home/home.dart
  lib/src/universal_ble.dart
  lib/src/universal_ble_linux/universal_ble_linux.dart
  lib/src/universal_ble_pigeon/universal_ble.g.dart
  lib/src/universal_ble_pigeon/universal_ble_pigeon_channel.dart
  lib/src/universal_ble_platform_interface.dart
  lib/src/universal_ble_web/universal_ble_web.dart
  pigeon/universal_ble.dart
  windows/src/generated/universal_ble.g.cpp
  windows/src/generated/universal_ble.g.h
  windows/src/universal_ble_plugin.cpp
  windows/src/universal_ble_plugin.h
Labels: Review effort [1-5]: 3
