Repository Navideck/universal_ble, pull requests merged in 2024-03, with the labels that each got.

#16 Fix windows release build compilation
  windows/src/helper/utils.h
  windows/src/universal_ble_plugin.cpp
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#17 Implement ScanFilter
  .vscode/settings.json
  CHANGELOG.md
  README.md
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBle.g.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBlePlugin.kt
  darwin/Classes/UniversalBle.g.swift
  darwin/Classes/UniversalBleHelper.swift
  darwin/Classes/UniversalBlePlugin.swift
  example/lib/data/mock_universal_ble.dart
  example/lib/home/home.dart
  lib/src/models/ble_scan_result.dart
  lib/src/models/model_exports.dart
  lib/src/models/scan_filter.dart
  lib/src/models/uuid.dart
  lib/src/models/web_request_options_builder.dart
  lib/src/universal_ble.dart
  lib/src/universal_ble_linux/universal_ble_linux.dart
  lib/src/universal_ble_pigeon/universal_ble.g.dart
  lib/src/universal_ble_pigeon/universal_ble_pigeon_channel.dart
  lib/src/universal_ble_platform_interface.dart
  lib/src/universal_ble_web/universal_ble_web.dart
  pigeon/universal_ble.dart
  pubspec.yaml
  windows/src/generated/universal_ble.g.cpp
  windows/src/generated/universal_ble.g.h
  windows/src/universal_ble_plugin.cpp
  windows/src/universal_ble_plugin.h
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#20 Fix windows crash when no bluetooth adapter available
  windows/src/universal_ble_plugin.cpp
Labels: Review effort [1-5]: 2, bug_fix

#22 Implement requestMtu in Linux
  README.md
  example/lib/data/capabilities.dart
  example/pubspec.lock
  lib/src/universal_ble_linux/universal_ble_linux.dart
  pubspec.yaml
Labels: enhancement, Review effort [1-5]: 2

#24 Fix wrong manufacturer data in release mode
  .vscode/settings.json
  example/lib/data/capabilities.dart
  example/lib/home/widgets/scanned_item_widget.dart
  lib/src/models/ble_scan_result.dart
  windows/src/helper/universal_enum.h
  windows/src/helper/utils.cpp
  windows/src/helper/utils.h
  windows/src/universal_ble_plugin.cpp
Labels: Review effort [1-5]: 2, bug_fix

#23 Add manufacturer data filtering
  .vscode/settings.json
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBle.g.kt
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
  darwin/Classes/UniversalBle.g.swift
  darwin/Classes/UniversalBleHelper.swift
  darwin/Classes/UniversalBlePlugin.swift
  example/lib/data/mock_universal_ble.dart
  example/lib/home/home.dart
  lib/src/models/model_exports.dart
  lib/src/models/scan_filter.dart
  lib/src/models/web_request_options_builder.dart
  lib/src/universal_ble.dart
  lib/src/universal_ble_linux/universal_ble_linux.dart
  lib/src/universal_ble_pigeon/universal_ble.g.dart
  lib/src/universal_ble_pigeon/universal_ble_pigeon_channel.dart
  lib/src/universal_ble_platform_interface.dart
  lib/src/universal_ble_web/universal_ble_web.dart
  pigeon/universal_ble.dart
  windows/src/generated/universal_ble.g.cpp
  windows/src/generated/universal_ble.g.h
  windows/src/universal_ble_plugin.cpp
  windows/src/universal_ble_plugin.h
Labels: enhancement, Review effort [1-5]: 4

#32 Fix discover services on Windows
  CHANGELOG.md
  pubspec.yaml
  windows/src/universal_ble_plugin.cpp
  windows/src/universal_ble_plugin.h
Labels: enhancement, Review effort [1-5]: 2
