Repository Navideck/universal_ble, pull requests merged in 2025-02, with the labels that each got.

#134 Update bluez.dart to 0.8.3
  pubspec.yaml
Labels: Review effort [1-5]: 1

#138 Do not normalize UUIDs on native side
  CHANGELOG.md
  android/src/main/kotlin/com/navideck/universal_ble/UniversalBleHelper.kt
  darwin/Classes/UniversalBleHelper.swift
  darwin/Classes/UniversalBlePlugin.swift
Labels: Review effort 2/5

#139 Improve ManufacturerDataFilter
  CHANGELOG.md
  README.md
  example/lib/home/widgets/scan_filter_widget.dart
  lib/src/models/manufacturer_data_filter.dart
  lib/src/models/model_exports.dart
  lib/src/models/scan_filter.dart
  lib/src/universal_ble_filter_util.dart
  lib/src/universal_ble_linux/universal_ble_linux.dart
  lib/src/universal_ble_pigeon/universal_ble_pigeon_channel.dart
  lib/src/universal_ble_web/universal_ble_web.dart
  test/manufacturer_data_filter_test.dart
  test/scan_filter_test.dart
Labels: Review effort 1/5

#140 Improve requestMTU() docs
  README.md
  lib/src/universal_ble.dart
Labels: Review effort 1/5

#141 Fix crash on Windows when calling pair APIs with an unknown deviceId
  CHANGELOG.md
  example/pubspec.lock
  pubspec.yaml
  windows/src/universal_ble_plugin.cpp
Labels: Review effort 2/5

#142 Fix: Unable to establish connection on channel when hot restart
  CHANGELOG.md
  windows/src/universal_ble_plugin.h
Labels: Review effort 1/5

#143 Fix Windows crash on start or stop scan
  CHANGELOG.md
  windows/src/universal_ble_plugin.cpp
  windows/src/universal_ble_plugin.h
Labels: Review effort 3/5
